DO $$
DECLARE
  v_state_id uuid;
BEGIN
  -- Oklahoma
  SELECT id INTO v_state_id FROM states WHERE code = 'OK';
  INSERT INTO counties (state_id, name) VALUES
    (v_state_id, 'Adair'), (v_state_id, 'Alfalfa'), (v_state_id, 'Atoka'),
    (v_state_id, 'Beaver'), (v_state_id, 'Beckham'), (v_state_id, 'Blaine'),
    (v_state_id, 'Bryan'), (v_state_id, 'Caddo'), (v_state_id, 'Canadian'),
    (v_state_id, 'Carter'), (v_state_id, 'Cherokee'), (v_state_id, 'Choctaw'),
    (v_state_id, 'Cimarron'), (v_state_id, 'Cleveland'), (v_state_id, 'Coal'),
    (v_state_id, 'Comanche'), (v_state_id, 'Cotton'), (v_state_id, 'Craig'),
    (v_state_id, 'Creek'), (v_state_id, 'Custer'), (v_state_id, 'Delaware'),
    (v_state_id, 'Dewey'), (v_state_id, 'Ellis'), (v_state_id, 'Garfield'),
    (v_state_id, 'Garvin'), (v_state_id, 'Grady'), (v_state_id, 'Grant'),
    (v_state_id, 'Greer'), (v_state_id, 'Harmon'), (v_state_id, 'Harper'),
    (v_state_id, 'Haskell'), (v_state_id, 'Hughes'), (v_state_id, 'Jackson'),
    (v_state_id, 'Jefferson'), (v_state_id, 'Johnston'), (v_state_id, 'Kay'),
    (v_state_id, 'Kingfisher'), (v_state_id, 'Kiowa'), (v_state_id, 'Latimer'),
    (v_state_id, 'Le Flore'), (v_state_id, 'Lincoln'), (v_state_id, 'Logan'),
    (v_state_id, 'Love'), (v_state_id, 'Major'), (v_state_id, 'Marshall'),
    (v_state_id, 'Mayes'), (v_state_id, 'McClain'), (v_state_id, 'McCurtain'),
    (v_state_id, 'McIntosh'), (v_state_id, 'Murray'), (v_state_id, 'Muskogee'),
    (v_state_id, 'Noble'), (v_state_id, 'Nowata'), (v_state_id, 'Okfuskee'),
    (v_state_id, 'Oklahoma'), (v_state_id, 'Okmulgee'), (v_state_id, 'Osage'),
    (v_state_id, 'Ottawa'), (v_state_id, 'Pawnee'), (v_state_id, 'Payne'),
    (v_state_id, 'Pittsburg'), (v_state_id, 'Pontotoc'), (v_state_id, 'Pottawatomie'),
    (v_state_id, 'Pushmataha'), (v_state_id, 'Roger Mills'), (v_state_id, 'Rogers'),
    (v_state_id, 'Seminole'), (v_state_id, 'Sequoyah'), (v_state_id, 'Stephens'),
    (v_state_id, 'Texas'), (v_state_id, 'Tillman'), (v_state_id, 'Tulsa'),
    (v_state_id, 'Wagoner'), (v_state_id, 'Washington'), (v_state_id, 'Washita'),
    (v_state_id, 'Woods'), (v_state_id, 'Woodward')
  ON CONFLICT (state_id, name) DO NOTHING;

  -- Oregon
  SELECT id INTO v_state_id FROM states WHERE code = 'OR';
  INSERT INTO counties (state_id, name) VALUES
    (v_state_id, 'Baker'), (v_state_id, 'Benton'), (v_state_id, 'Clackamas'),
    (v_state_id, 'Clatsop'), (v_state_id, 'Columbia'), (v_state_id, 'Coos'),
    (v_state_id, 'Crook'), (v_state_id, 'Curry'), (v_state_id, 'Deschutes'),
    (v_state_id, 'Douglas'), (v_state_id, 'Gilliam'), (v_state_id, 'Grant'),
    (v_state_id, 'Harney'), (v_state_id, 'Hood River'), (v_state_id, 'Jackson'),
    (v_state_id, 'Jefferson'), (v_state_id, 'Josephine'), (v_state_id, 'Klamath'),
    (v_state_id, 'Lake'), (v_state_id, 'Lane'), (v_state_id, 'Lincoln'),
    (v_state_id, 'Linn'), (v_state_id, 'Malheur'), (v_state_id, 'Marion'),
    (v_state_id, 'Morrow'), (v_state_id, 'Multnomah'), (v_state_id, 'Polk'),
    (v_state_id, 'Sherman'), (v_state_id, 'Tillamook'), (v_state_id, 'Umatilla'),
    (v_state_id, 'Union'), (v_state_id, 'Wallowa'), (v_state_id, 'Wasco'),
    (v_state_id, 'Washington'), (v_state_id, 'Wheeler'), (v_state_id, 'Yamhill')
  ON CONFLICT (state_id, name) DO NOTHING;

  -- Pennsylvania
  SELECT id INTO v_state_id FROM states WHERE code = 'PA';
  INSERT INTO counties (state_id, name) VALUES
    (v_state_id, 'Adams'), (v_state_id, 'Allegheny'), (v_state_id, 'Armstrong'),
    (v_state_id, 'Beaver'), (v_state_id, 'Bedford'), (v_state_id, 'Berks'),
    (v_state_id, 'Blair'), (v_state_id, 'Bradford'), (v_state_id, 'Bucks'),
    (v_state_id, 'Butler'), (v_state_id, 'Cambria'), (v_state_id, 'Cameron'),
    (v_state_id, 'Carbon'), (v_state_id, 'Centre'), (v_state_id, 'Chester'),
    (v_state_id, 'Clarion'), (v_state_id, 'Clearfield'), (v_state_id, 'Clinton'),
    (v_state_id, 'Columbia'), (v_state_id, 'Crawford'), (v_state_id, 'Cumberland'),
    (v_state_id, 'Dauphin'), (v_state_id, 'Delaware'), (v_state_id, 'Elk'),
    (v_state_id, 'Erie'), (v_state_id, 'Fayette'), (v_state_id, 'Forest'),
    (v_state_id, 'Franklin'), (v_state_id, 'Fulton'), (v_state_id, 'Greene'),
    (v_state_id, 'Huntingdon'), (v_state_id, 'Indiana'), (v_state_id, 'Jefferson'),
    (v_state_id, 'Juniata'), (v_state_id, 'Lackawanna'), (v_state_id, 'Lancaster'),
    (v_state_id, 'Lawrence'), (v_state_id, 'Lebanon'), (v_state_id, 'Lehigh'),
    (v_state_id, 'Luzerne'), (v_state_id, 'Lycoming'), (v_state_id, 'McKean'),
    (v_state_id, 'Mercer'), (v_state_id, 'Mifflin'), (v_state_id, 'Monroe'),
    (v_state_id, 'Montgomery'), (v_state_id, 'Montour'), (v_state_id, 'Northampton'),
    (v_state_id, 'Northumberland'), (v_state_id, 'Perry'), (v_state_id, 'Philadelphia'),
    (v_state_id, 'Pike'), (v_state_id, 'Potter'), (v_state_id, 'Schuylkill'),
    (v_state_id, 'Snyder'), (v_state_id, 'Somerset'), (v_state_id, 'Sullivan'),
    (v_state_id, 'Susquehanna'), (v_state_id, 'Tioga'), (v_state_id, 'Union'),
    (v_state_id, 'Venango'), (v_state_id, 'Warren'), (v_state_id, 'Washington'),
    (v_state_id, 'Wayne'), (v_state_id, 'Westmoreland'), (v_state_id, 'Wyoming'),
    (v_state_id, 'York')
  ON CONFLICT (state_id, name) DO NOTHING;

  -- Texas
  SELECT id INTO v_state_id FROM states WHERE code = 'TX';
  INSERT INTO counties (state_id, name) VALUES
    (v_state_id, 'Anderson'), (v_state_id, 'Andrews'), (v_state_id, 'Angelina'),
    (v_state_id, 'Aransas'), (v_state_id, 'Archer'), (v_state_id, 'Armstrong'),
    (v_state_id, 'Atascosa'), (v_state_id, 'Austin'), (v_state_id, 'Bailey'),
    (v_state_id, 'Bandera'), (v_state_id, 'Bastrop'), (v_state_id, 'Baylor'),
    (v_state_id, 'Bee'), (v_state_id, 'Bell'), (v_state_id, 'Bexar'),
    (v_state_id, 'Blanco'), (v_state_id, 'Borden'), (v_state_id, 'Bosque'),
    (v_state_id, 'Bowie'), (v_state_id, 'Brazoria'), (v_state_id, 'Brazos'),
    (v_state_id, 'Brewster'), (v_state_id, 'Briscoe'), (v_state_id, 'Brooks'),
    (v_state_id, 'Brown'), (v_state_id, 'Burleson'), (v_state_id, 'Burnet'),
    (v_state_id, 'Caldwell'), (v_state_id, 'Calhoun'), (v_state_id, 'Callahan'),
    (v_state_id, 'Cameron'), (v_state_id, 'Camp'), (v_state_id, 'Carson'),
    (v_state_id, 'Cass'), (v_state_id, 'Castro'), (v_state_id, 'Chambers'),
    (v_state_id, 'Cherokee'), (v_state_id, 'Childress'), (v_state_id, 'Clay'),
    (v_state_id, 'Cochran'), (v_state_id, 'Coke'), (v_state_id, 'Coleman'),
    (v_state_id, 'Collin'), (v_state_id, 'Collingsworth'), (v_state_id, 'Colorado'),
    (v_state_id, 'Comal'), (v_state_id, 'Comanche'), (v_state_id, 'Concho'),
    (v_state_id, 'Cooke'), (v_state_id, 'Coryell'), (v_state_id, 'Cottle'),
    (v_state_id, 'Crane'), (v_state_id, 'Crockett'), (v_state_id, 'Crosby'),
    (v_state_id, 'Culberson'), (v_state_id, 'Dallam'), (v_state_id, 'Dallas'),
    (v_state_id, 'Dawson'), (v_state_id, 'Deaf Smith'), (v_state_id, 'Delta'),
    (v_state_id, 'Denton'), (v_state_id, 'DeWitt'), (v_state_id, 'Dickens'),
    (v_state_id, 'Dimmit'), (v_state_id, 'Donley'), (v_state_id, 'Duval'),
    (v_state_id, 'Eastland'), (v_state_id, 'Ector'), (v_state_id, 'Edwards'),
    (v_state_id, 'El Paso'), (v_state_id, 'Ellis'), (v_state_id, 'Erath'),
    (v_state_id, 'Falls'), (v_state_id, 'Fannin'), (v_state_id, 'Fayette'),
    (v_state_id, 'Fisher'), (v_state_id, 'Floyd'), (v_state_id, 'Foard'),
    (v_state_id, 'Fort Bend'), (v_state_id, 'Franklin'), (v_state_id, 'Freestone'),
    (v_state_id, 'Frio'), (v_state_id, 'Gaines'), (v_state_id, 'Galveston'),
    (v_state_id, 'Garza'), (v_state_id, 'Gillespie'), (v_state_id, 'Glasscock'),
    (v_state_id, 'Goliad'), (v_state_id, 'Gonzales'), (v_state_id, 'Gray'),
    (v_state_id, 'Grayson'), (v_state_id, 'Gregg'), (v_state_id, 'Grimes'),
    (v_state_id, 'Guadalupe'), (v_state_id, 'Hale'), (v_state_id, 'Hall'),
    (v_state_id, 'Hamilton'), (v_state_id, 'Hansford'), (v_state_id, 'Hardeman'),
    (v_state_id, 'Hardin'), (v_state_id, 'Harris'), (v_state_id, 'Harrison'),
    (v_state_id, 'Hartley'), (v_state_id, 'Haskell'), (v_state_id, 'Hays'),
    (v_state_id, 'Hemphill'), (v_state_id, 'Henderson'), (v_state_id, 'Hidalgo'),
    (v_state_id, 'Hill'), (v_state_id, 'Hockley'), (v_state_id, 'Hood'),
    (v_state_id, 'Hopkins'), (v_state_id, 'Houston'), (v_state_id, 'Howard'),
    (v_state_id, 'Hudspeth'), (v_state_id, 'Hunt'), (v_state_id, 'Hutchinson'),
    (v_state_id, 'Irion'), (v_state_id, 'Jack'), (v_state_id, 'Jackson'),
    (v_state_id, 'Jasper'), (v_state_id, 'Jeff Davis'), (v_state_id, 'Jefferson'),
    (v_state_id, 'Jim Hogg'), (v_state_id, 'Jim Wells'), (v_state_id, 'Johnson'),
    (v_state_id, 'Jones'), (v_state_id, 'Karnes'), (v_state_id, 'Kaufman'),
    (v_state_id, 'Kendall'), (v_state_id, 'Kenedy'), (v_state_id, 'Kent'),
    (v_state_id, 'Kerr'), (v_state_id, 'Kimble'), (v_state_id, 'King'),
    (v_state_id, 'Kinney'), (v_state_id, 'Kleberg'), (v_state_id, 'Knox'),
    (v_state_id, 'La Salle'), (v_state_id, 'Lamar'), (v_state_id, 'Lamb'),
    (v_state_id, 'Lampasas'), (v_state_id, 'Lavaca'), (v_state_id, 'Lee'),
    (v_state_id, 'Leon'), (v_state_id, 'Liberty'), (v_state_id, 'Limestone'),
    (v_state_id, 'Lipscomb'), (v_state_id, 'Live Oak'), (v_state_id, 'Llano'),
    (v_state_id, 'Loving'), (v_state_id, 'Lubbock'), (v_state_id, 'Lynn'),
    (v_state_id, 'Madison'), (v_state_id, 'Marion'), (v_state_id, 'Martin'),
    (v_state_id, 'Mason'), (v_state_id, 'Matagorda'), (v_state_id, 'Maverick'),
    (v_state_id, 'McCulloch'), (v_state_id, 'McLennan'), (v_state_id, 'McMullen'),
    (v_state_id, 'Medina'), (v_state_id, 'Menard'), (v_state_id, 'Midland'),
    (v_state_id, 'Milam'), (v_state_id, 'Mills'), (v_state_id, 'Mitchell'),
    (v_state_id, 'Montague'), (v_state_id, 'Montgomery'), (v_state_id, 'Moore'),
    (v_state_id, 'Morris'), (v_state_id, 'Motley'), (v_state_id, 'Nacogdoches'),
    (v_state_id, 'Navarro'), (v_state_id, 'Newton'), (v_state_id, 'Nolan'),
    (v_state_id, 'Nueces'), (v_state_id, 'Ochiltree'), (v_state_id, 'Oldham'),
    (v_state_id, 'Orange'), (v_state_id, 'Palo Pinto'), (v_state_id, 'Panola'),
    (v_state_id, 'Parker'), (v_state_id, 'Parmer'), (v_state_id, 'Pecos'),
    (v_state_id, 'Polk'), (v_state_id, 'Potter'), (v_state_id, 'Presidio'),
    (v_state_id, 'Rains'), (v_state_id, 'Randall'), (v_state_id, 'Reagan'),
    (v_state_id, 'Real'), (v_state_id, 'Red River'), (v_state_id, 'Reeves'),
    (v_state_id, 'Refugio'), (v_state_id, 'Roberts'), (v_state_id, 'Robertson'),
    (v_state_id, 'Rockwall'), (v_state_id, 'Runnels'), (v_state_id, 'Rusk'),
    (v_state_id, 'Sabine'), (v_state_id, 'San Augustine'), (v_state_id, 'San Jacinto'),
    (v_state_id, 'San Patricio'), (v_state_id, 'San Saba'), (v_state_id, 'Schleicher'),
    (v_state_id, 'Scurry'), (v_state_id, 'Shackelford'), (v_state_id, 'Shelby'),
    (v_state_id, 'Sherman'), (v_state_id, 'Smith'), (v_state_id, 'Somervell'),
    (v_state_id, 'Starr'), (v_state_id, 'Stephens'), (v_state_id, 'Sterling'),
    (v_state_id, 'Stonewall'), (v_state_id, 'Sutton'), (v_state_id, 'Swisher'),
    (v_state_id, 'Tarrant'), (v_state_id, 'Taylor'), (v_state_id, 'Terrell'),
    (v_state_id, 'Terry'), (v_state_id, 'Throckmorton'), (v_state_id, 'Titus'),
    (v_state_id, 'Tom Green'), (v_state_id, 'Travis'), (v_state_id, 'Trinity'),
    (v_state_id, 'Tyler'), (v_state_id, 'Upshur'), (v_state_id, 'Upton'),
    (v_state_id, 'Uvalde'), (v_state_id, 'Val Verde'), (v_state_id, 'Van Zandt'),
    (v_state_id, 'Victoria'), (v_state_id, 'Walker'), (v_state_id, 'Waller'),
    (v_state_id, 'Ward'), (v_state_id, 'Washington'), (v_state_id, 'Webb'),
    (v_state_id, 'Wharton'), (v_state_id, 'Wheeler'), (v_state_id, 'Wichita'),
    (v_state_id, 'Wilbarger'), (v_state_id, 'Willacy'), (v_state_id, 'Williamson'),
    (v_state_id, 'Wilson'), (v_state_id, 'Winkler'), (v_state_id, 'Wise'),
    (v_state_id, 'Wood'), (v_state_id, 'Yoakum'), (v_state_id, 'Young'),
    (v_state_id, 'Zapata'), (v_state_id, 'Zavala')
  ON CONFLICT (state_id, name) DO NOTHING;

END $$;